// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClFPF9B3tw2444WYEy30vo2rkNapOCWdY',
    appId: '1:1053000782693:web:0f8ab50c1a54ce3040878c',
    messagingSenderId: '1053000782693',
    projectId: 'human-rights-tracker-5822f',
    authDomain: 'human-rights-tracker-5822f.firebaseapp.com',
    storageBucket: 'human-rights-tracker-5822f.firebasestorage.app',
    measurementId: 'G-ZKTV3FYLLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6nCKIfn7Wb25V3WLaTSzYCzSa1kXVSdA',
    appId: '1:1053000782693:android:fe8d45087bcda6c340878c',
    messagingSenderId: '1053000782693',
    projectId: 'human-rights-tracker-5822f',
    storageBucket: 'human-rights-tracker-5822f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxrWIlyRWnjXCiXHq7yG2ZWwPkyZUYTBw',
    appId: '1:1053000782693:ios:30c178843713091940878c',
    messagingSenderId: '1053000782693',
    projectId: 'human-rights-tracker-5822f',
    storageBucket: 'human-rights-tracker-5822f.firebasestorage.app',
    iosBundleId: 'com.example.humanRightsTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxrWIlyRWnjXCiXHq7yG2ZWwPkyZUYTBw',
    appId: '1:1053000782693:ios:30c178843713091940878c',
    messagingSenderId: '1053000782693',
    projectId: 'human-rights-tracker-5822f',
    storageBucket: 'human-rights-tracker-5822f.firebasestorage.app',
    iosBundleId: 'com.example.humanRightsTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClFPF9B3tw2444WYEy30vo2rkNapOCWdY',
    appId: '1:1053000782693:web:4ff79c64b7c501b440878c',
    messagingSenderId: '1053000782693',
    projectId: 'human-rights-tracker-5822f',
    authDomain: 'human-rights-tracker-5822f.firebaseapp.com',
    storageBucket: 'human-rights-tracker-5822f.firebasestorage.app',
    measurementId: 'G-12W2YR0T6K',
  );

}