name: human_rights_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.1
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  file_picker: ^8.0.3
  firebase_storage: ^11.7.7
  step_progress_indicator: ^1.0.2
  timeline_tile: ^2.0.0
  fl_chart: ^0.69.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app-logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app-logo.png"
